
indent_style = "Visual"
binop_separator = "Front"
wrap_comments = true
comment_width = 80
max_width = 80
use_small_heuristics = "Off"
imports_layout = "Horizontal"
match_block_trailing_comma = true
reorder_impl_items = true
use_field_init_shorthand = true
